In [4]:
list = [i for i in range(1,11)]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
list[3:]

[4, 5, 6, 7, 8, 9, 10]

In [10]:
list[:3]

[1, 2, 3]

In [12]:
list[3:8]

[4, 5, 6, 7, 8]

In [15]:
list[-2:]

[9, 10]

In [18]:
list[:-2]

[1, 2, 3, 4, 5, 6, 7, 8]

In [20]:
generator = [x for x in range(1,5)]
matrix = [generator for e in range(1,5)]
matrix

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

In [95]:
# matrix generator
import random as rnd

def rowGenerator(length):
    rowList = []
    for x in range(length):
        rand = rnd.randrange(0,15)
        rowList.append(rand)
    return rowList

def generator(row,column):
    rowList = []
    matrix = []
    for x in range(row):
        for i in range(column):
            rowList = rowGenerator(row)
            matrix.append(rowList)
    return matrix

matrix = generator(3,3)
matrix

[[3, 7, 7],
 [6, 4, 12],
 [8, 9, 13],
 [14, 4, 7],
 [0, 8, 8],
 [13, 4, 11],
 [6, 12, 13],
 [3, 0, 9],
 [7, 10, 13]]

In [101]:
import numpy as np
np.arange(5,21,5)

array([ 5, 10, 15, 20])

In [103]:
np.array(matrix)

array([[ 3,  7,  7],
       [ 6,  4, 12],
       [ 8,  9, 13],
       [14,  4,  7],
       [ 0,  8,  8],
       [13,  4, 11],
       [ 6, 12, 13],
       [ 3,  0,  9],
       [ 7, 10, 13]])

In [109]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [115]:
np.random.randn(3,3)

array([[ 0.86166636, -0.5350937 , -0.47082072],
       [-0.22380547,  1.47483989,  0.11464786],
       [ 0.32687406, -1.09254627, -1.06183151]])