In [47]:
import numpy as np
matrix = [[10,20,30],[421,124,2155],[1246,42135,2321],[123,42135,214],[124312,214,124324]]
matrix[2][2]

2321

In [48]:
matrix[:2]

[[10, 20, 30], [421, 124, 2155]]

In [55]:
matrix[1:][:1]

array([[ 421,  124, 2155]])

In [57]:
matrix[3,1]

42135

In [50]:
matrix = np.array(matrix)
matrix

array([[    10,     20,     30],
       [   421,    124,   2155],
       [  1246,  42135,   2321],
       [   123,  42135,    214],
       [124312,    214, 124324]])

In [54]:
matrix[1:,1:]

array([[   124,   2155],
       [ 42135,   2321],
       [ 42135,    214],
       [   214, 124324]])

In [61]:
matrix[[0,2,4]]

array([[    10,     20,     30],
       [  1246,  42135,   2321],
       [124312,    214, 124324]])

In [63]:
matrix.size

15

In [66]:
matrix.dtype.name

'int64'

In [75]:
newMatrix = matrix.reshape(matrix.size)
newMatrix

array([    10,     20,     30,    421,    124,   2155,   1246,  42135,
         2321,    123,  42135,    214, 124312,    214, 124324])

In [76]:
newMatrix.dtype.name

'int64'

In [83]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
aa = np.array(a)
print(aa*2)
bb = np.array(b)
print(bb-2)
print(np.sin(aa))

[ 2  4  6  8 10]
[4 5 6 7 8]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [86]:
x=np.array([[1,2,3,4],
            [1,2,3,4]])

y=np.array([[1,2,3,4],
            [1,2,3,4]])

print(x+y)
print(y.T)
xy=x.dot(y.T) # Returns the multiply of two matrices 
print(xy)
print(np.exp(xy))

[[2 4 6 8]
 [2 4 6 8]]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[30 30]
 [30 30]]
[[1.06864746e+13 1.06864746e+13]
 [1.06864746e+13 1.06864746e+13]]


In [101]:
randommatris=np.random.random((4,5))
print(randommatris)
print(randommatris.sum())

[[0.55742272 0.83479936 0.80070326 0.78039072 0.16209675]
 [0.69711451 0.46686352 0.7755177  0.05066851 0.41912544]
 [0.33078231 0.9866015  0.75836556 0.28419386 0.18179753]
 [0.28176103 0.88813392 0.67989556 0.17355704 0.99682966]]
11.106620472417651


In [107]:
print(randommatris.sum(axis=0))#columns sum
print(randommatris.sum(axis=1))#columns sum

[1.86708057 3.1763983  3.01448208 1.28881014 1.75984938]
[3.13541281 2.40928969 2.54174076 3.02017722]


In [113]:
a = np.array([[1, 2, 3], [4, 5, 9]])
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))

[[1 2 3]
 [4 5 9]]
[ 5  7 12]
[ 6 18]


In [117]:
print(np.sqrt(a))
print(np.square(a))
print(np.add(x,y))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 3.        ]]
[[ 1  4  9]
 [16 25 81]]
[[2 4 6 8]
 [2 4 6 8]]


In [136]:
nplist = np.array([1,2,3,4,5,6,7,8])
nplist2 = np.array([11,22,33,44,55,66,77,88])

In [137]:
vertical=np.vstack((nplist,nplist2))
print(vertical)
print(vertical.ndim)
horizontal = np.hstack((nplist,nplist2))
print(horizontal)
print(horizontal.ndim)

[[ 1  2  3  4  5  6  7  8]
 [11 22 33 44 55 66 77 88]]
2
[ 1  2  3  4  5  6  7  8 11 22 33 44 55 66 77 88]
1


In [138]:
vertical1 = np.row_stack((nplist,nplist2))
print(vertical1)
print(vertical1.ndim)
horizontal1 = np.column_stack((nplist,nplist2))
print(horizontal1)
print(horizontal1.ndim)

[[ 1  2  3  4  5  6  7  8]
 [11 22 33 44 55 66 77 88]]
2
[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]
 [ 7 77]
 [ 8 88]]
2


In [140]:
v2=np.stack((nplist,nplist2),axis=-1)
print(v2)
h2=np.stack((nplist,nplist2),axis=0)
print(h2)

[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]
 [ 7 77]
 [ 8 88]]
[[ 1  2  3  4  5  6  7  8]
 [11 22 33 44 55 66 77 88]]


In [143]:
horizontal.resize(4,4)
edit=horizontal.ravel()
edit

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 22, 33, 44, 55, 66, 77, 88])

In [146]:
print(horizontal[:,:])
print(horizontal[:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]
 [55 66 77 88]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]
 [55 66 77 88]]


In [147]:
print(vertical[1:3,1:])

[[22 33 44 55 66 77 88]]
